name: lint and deploy

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Cache node.js modules
        uses: actions/cache@v2
        env:
          cache-name: npm-${{ hashFiles('package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-key: |
            ${{ env.cache-name }}
      - name: Install dependencies
        run: npm install
      - name: Lint source code with ESLint
        run: npm run lint

  prettier:
    runs-on: ubuntu-latest
    container:
      image: node:14.17.0-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Cache node.js modules
        uses: actions/cache@v2
        env:
          cache-name: npm-${{ hashFiles('package-lock.json') }}
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}
          restore-key: |
            ${{ env.cache-name }}
      - name: Install dependencies
        run: npm install
      - name: Check with Prettier
        run: npm run check:format
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          - rsync -a --progress --human-readable --delete \
          --exclude-from '.gitignore' \
          --exclude .gitignore \
          --exclude .git \
          . deploy@185.251.90.153:~/realworld/
          - ssh deploy@185.251.90.153 "pushd ~/realworld && npm install && pm2 restart realworld && popd"
        env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
         SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

